### ISSUE TITLE
Output in compact mode

### ISSUE THREAD

**Issue by niceoutput** [frontendfriends/gulp-combine-mq#8]
There's a way to output in compact mode instead of expanded?

**Comment by furzeface** [comment]
I've just implemented this and released [0.4.0](https://github.com/frontendfriends/gulp-combine-mq/releases/tag/v0.4.0). 

I've updated [README.md with options](https://github.com/frontendfriends/gulp-combine-mq#usage) - let me know how it goes.

**Comment by niceoutput** [comment]
Hi @furzeface ,
The beautify option set to false only remove the identation. 
All i want is the option to output the css in :compact mode like sass did.

Thanks

**Comment by furzeface** [comment]
In that case, no I'm afraid not. Are you using this task to combine media queries in scss files? 

What's the reason for needing it formatted as such, just out of curiosity?



---


- http://furzeface.com/blog

- @furzeface

**Comment by niceoutput** [comment]
@furzeface i use this plugin in the .css not in the .scss.
If i could use this to combine media queries in .scss it would be great because i use nested media queries inside the css classes.

I hope you understand my problem.

**Comment by furzeface** [comment]
It achieves the same output if you use it on your compiled CSS files, are you able to do that in your project?
